[package]
name = "ljmrs"
version = "0.1.1"
description = "LabJack LJM Bindings for Rust"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.8"
serde = { version = "1.0.192", features = ["std", "derive"], optional = true }

[features]
default = []

[lib]
name = "ljmrs"
path = "src/lib.rs"
