[package]
name = "ljmrs"
version = "0.0.14"
description = "Labjack LJM Bindings for Rust"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.8"

[lib]
name = "ljmrs"
path = "src/lib.rs"

